---
title: "Data exploration: ggplot2 Basics"
# subtitle: "(according to Hadley Wickham/RStudio)"
author: "Johannes Breuer<br />Thomas Ebel<br />Stefan Müller"
date: "2019-05-15"
location: "GESIS, Mannheim, Germany"
output:
  xaringan::moon_reader:
  lib_dir: libs
css: ["default", "robot-fonts", "../footer-header.css", "../mycss.css"]
nature:
  highlightStyle: "github"
highlightLines: true
countIncrementalSlides: false
---
  layout: true

```{r setup, include = FALSE}
packages_to_load <- c("knitr", "rmarkdown", "magrittr", "readr", "ggplot2")

for (i in packages_to_load) {
  if (!require(i, character.only = TRUE)) {
    install.packages(i)
  } else {
    library(i, character.only = TRUE)
  }
}

rm(packages_to_load)

options(htmltools.dir.version = FALSE)

opts_chunk$set(echo = FALSE, fig.align = "center")
```

<div class="my-footer">
  <div style="float: left;"><span>`r gsub("<br />", " & ", gsub("<br /><br />|<a.+$", "", metadata$author))`</span></div>
  <div style="float: right;"><span>`r metadata$location`, `r metadata$date`</span></div>
  <div style="text-align: center;"><span>`r gsub(".+<br />", " ", metadata$title)`</span></div>
  </div>
  
---
# What is ggplot2?
`ggplot2` is an R-package to create plots.

It uses the "grammar of graphics"

- language for multi-dimensional and data
- accordingly, it expects (a) data (frame) as input
- components of the plot are added as layers

---
# Going deeper into the components of a plot
According to Wickham (2010, 8) a layered plot consists of the following components:

- data and aesthetic mappings,
- geometric objects,
- scales,
- and facet specification
  
---
# Data requirements
You can use one single data frame to create a plot in `ggplot2`.

As such, everything's on the plot is data, which creates a nice and smooth workflow from data wrangling to the final presentation of the results.

But this makes it difficult to add extra features to your plot.

  - There are ways of doing it anyway as we will see later
  - Yet, it requires thinking about what to plot

---
# Why the long data format?
`ggplot2` requires data to be in the long data format.

In some scientific disciplines this format is only used for some specialized analyses, e.g., time series analysis

We should get used to it anyway as the long table format has some very important benefits
- every element we aim to plot is just an observation
  - no thinking required how a specific variable relates to an observation
- most importantly, the long format is more parsimonious
  - it requires less memory and less disk space for processing
  
---
# Enough is enough: I want to see a plot

---
# Exercise: plots
  
  
  
  
  
  
  
  