---
title: 'Exercises Data Wrangling 1 - Solutions'
author: 'Johannes Breuer, Stefan Jünger, Thomas Ebel'
date: 'Data Wrangling & Exploration with the Tidyverse in R, May 15-16, 2019'
output:
  unilur::tutorial_html_solution: default
  #unilur::tutorial_html: default
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
# custom boxes
knitr::opts_template$set(clues = list(box.title = "Clues",
                                      box.body = list(fill = "#fff9dc", colour = "black"),
                                      box.header = list(fill = "#ffec8b", colour = "black"),
                                      box.icon = "fa-search",
                                      box.collapse = TRUE))
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```

In the following exercises we will wrangle some data on population from [*Gapminder*](https://www.gapminder.org/).

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Read in the *Gapminder* population data and store it as a new object called *gap_pop*.
```

```{block, opts.label = "clues"}
The data we need is stored in a .csv file which you can find in the folder *data/gapminder*. NB: We will keep it in the wide format for now.
```

```{r read gap_pop, solution = TRUE}
gap_pop <- read_csv("../data/gapminder/population_total.csv")
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Rename the variable *Total population* to *country* and store the result in an object with the same name (*gap_pop*).
```

```{r rename, solution = TRUE}
gap_pop <- gap_pop %>% 
  rename(country = "Total population")
```

```{block, solution = TRUE}
The dataset is in *wide format* with each year as a column/variable. To increase human-readability and to facilitate further data wrangling and exploration steps, it makes sense to transform it into *long format*.
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Transform the *gap_life* dataset into a sensible long format.
```

```{block, opts.label = "clues"}
You should `gather` the years into one column/variable. If you are unsure about the arguments of a function, you can always consult the help files by typing (and running) a ? directly followed by the function name (e.g., `?glimpse`). NB: This only works if you have previously loaded the package that includes the function.

Be aware that there is one column in the dataset that you do not want to gather. You can specify this by adding -variablename as the second argument (or first if you use pipes) to the `gather()` function.
```

```{r gap long, solution = TRUE}
gap_life_long <- gap_life %>% 
  gather(-country, key = "year", value = "life_exp")

gap_life_long
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Have a look at the *crime* dataset. What do you notice?
```

```{block, solution = TRUE}
Observations are spread across two rows. The intepretation of the *value* column depends on the value of *crime*.
```

```{block, box.title = "4", box.body = list(fill = "white"), box.icon = "fa-star"}
Tidy the *crime* dataset, so that there is only one observation/row for each country.
```

```{block, opts.label = "clues"}
You should `spread` the *crime* variable.
```

```{r crime spread, solution = TRUE}
crime_spread <- crime %>% 
  spread(key = "crime", value = "value")

crime_spread
```

```{block, box.title = "5", box.body = list(fill = "white"), box.icon = "fa-star"}
Split the *Name* variable in the *titanic* dataset into two variables: one that contains only the last name, and one that contains the first name(s) plus title (Mr., Mrs., Dr., etc.).
```

```{block, opts.label = "clues"}
When looking at the *Name* variable in the *titanic* dataset you should notice that the last name is separated from the rest of the name by a comma plus a space.
```

```{r titanic names, solution = TRUE}
titanic <- titanic %>% 
  separate(Name, c("last_name", "first_name"), sep =", ")

titanic
```